blog/albums/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from blog.routers import CustomRouter
from albums.api.views import AlbumViewSet, DraftAlbumViewSet

router = CustomRouter()
# router.register(r'draft', DraftPostViewSet, basename='draft')
router.register(r'', AlbumViewSet, basename='post')
router.register(r'draft', DraftAlbumViewSet, basename='draft') 


urlpatterns = [
    path('', include(router.urls)),
]

blog/albums/urls.py
from django.urls import path
from albums.views import (
    index,
    create,
    show,
    edit,
    draft_album_create
)


urlpatterns = [
    path('', index, name='index'),
    path('blog/<slug:slug>/create/', create, name='create'),
    path('show/<slug:slug>/', show, name="show"),
    path('edit/<slug:slug>/', edit, name="edit"),
    path('blog/<slug:slug>/draft/create/', draft_album_create, name="draft_album_create"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import redirect_main
from blog.admin import login, logout

from blogs.views import best_blogs, search, search_tags, main, popular, popular_users

from scheduler.scheduler import TasksScheduler

from .swagger import urlpatterns as urlpatterns_swagger

urlpatterns = [
    # path('admin/login/', login),
    # path('admin/logout/', logout),
    path('admin/', admin.site.urls),

    path('', redirect_main, name="redirect_main"),
    path('main/', main, name="main"),
    path('popular/', popular, name="popular"),
    path('popular_users/', popular_users, name="popular_users"),
    path('best_blogs/', best_blogs, name="best_blogs"),
    path('search/<str:q>/', search, name="search"),
    path('search_tags/<str:q>/', search_tags, name="search_tags"),

    path('', include(('users.urls', 'users'), namespace="users")),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace="blogs")),
    path('posts/', include(('posts.urls', 'posts'), namespace="posts")),
    # path('drafts/', include(('drafts.urls', 'drafts'), namespace="drafts")),
    # path('drafts_survey/', include(('drafts_survey.urls', 'drafts_survey'), namespace="drafts_survey")),
    path('surveys/', include(('surveys.urls', 'surveys'), namespace="surveys")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),
    path('albums/', include(('albums.urls', 'albums'), namespace="albums")),
    path('tests/', include('custom_tests.urls')),
    path('quests/', include('quests.urls')),
    path('companies/', include('campaign.urls')),
    path('periodic_bonuses/', include('periodic_bonuses.urls')),
    path('contests/', include(('contests.urls', 'contests'), namespace="contests")),

    path('summernote/', include('django_summernote.urls')),
    path('api/v1/blogs/', include('blogs.api.urls')),
    path('api/v1/users/', include('users.api.urls')),
    path('api/v1/posts/', include('posts.api.urls')),
    path('api/v1/surveys/', include('surveys.api.urls')),
    # # path('api/v1/drafts/', include('drafts.api.urls')),
    # # path('api/v1/drafts_survey/', include('drafts_survey.api.urls')),
    path('api/v1/comments/', include('comments.api.urls')),
    path('api/v1/notifications/', include('notifications.api.urls')),
    path('api/v1/tests/', include('custom_tests.api.urls')),
    path('api/v1/quests/', include('quests.api.urls')),
    path('api/v1/companies/', include('campaign.api.urls')),
    path('api/v1/periodic_bonuses/', include('periodic_bonuses.api.urls')),
    path('api/v1/albums/', include('albums.api.urls')),
    path('api/v1/contests/', include('contests.api.urls')),
    
    # path('language/<str:language>/', language, name="language"),

    *urlpatterns_swagger
]

# running scheduler
try:
    scheduler = TasksScheduler()
    scheduler.run()
except Exception as e:
    print(f"Scheduler error: {e}")

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/users/urls.py
from django.urls import path
# from unfold.admin import site
from users.views import *


urlpatterns = [
    path("registration/login/", login_register, name="login_register"),
    path("my/profile/", my_profile, name="my_profile"),
    path("profile/<str:username>/", profile, name="profile"),
    path("forgot_password/", forgot_password, name="forgot_password"),
    path("change_password/<uidb64>/<token>/", change_password, name="change_password"),
    path("edit_profile", edit_profile, name="edit_profile"),
    path("edit_password", edit_password, name="edit_password"),
    path("change_user_status", change_user_status, name="change_user_status"),
    # path("my_page/", site.admin_view(MyCustomPage.as_view()), name="my_page"),
]


# site.register_view(path="my-custom-page/", view=MyCustomPage, name="my_custom_page")

blog/albums/models.py
from django.db import models
from django.conf import settings
from blog.managers import LevelAccessManager
from blogs.models import Blog, LevelAccess
from django.template.defaultfilters import slugify as default_slugify
from transliterate import slugify
from django_cleanup import cleanup
from blog.utils import upload_to, change_size
from django.utils import timezone
import time


class Category(models.Model):
    category_rus = models.CharField(verbose_name='Category rus')
    category_eng = models.CharField(verbose_name='Category eng')
    
    def __str__(self):
        return self.category_eng
    
    
class Subcategory(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory_rus = models.CharField(verbose_name='Subcategory rus')
    subcategory_eng = models.CharField(verbose_name='Subcategory eng')

    def __str__(self):
        return self.subcategory_eng


class Album(models.Model):
    level_access_objects = LevelAccessManager()
    objects = models.Manager()

    slug = models.SlugField(
        verbose_name="URL", max_length=255, unique=True, db_index=True
    )
    preview = models.ImageField(
        verbose_name="Preview", upload_to=upload_to("uploads/albums/previews"), null=True, blank=True
    )
    size = models.IntegerField(blank=True, verbose_name='Size preview (KB)', null=True)
    title = models.CharField(
        verbose_name="Title", null=False, blank=False, max_length=255
    )
    description = models.TextField(verbose_name='Description')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    language = models.CharField(
        max_length=255,
        verbose_name="Language"
    )
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    hide_to_user = models.BooleanField(default=False, verbose_name="Hide to user")
    hide_to_moderator = models.BooleanField(
        default=False, verbose_name="Hide to moderator"
    )
    namespace = models.CharField(verbose_name='Namespace', default='albums')
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True)
    preview_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = "Album"
        verbose_name_plural = "Albums"
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_preview = self.preview

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.blog.is_private and self.level_access:
            self.level_access = None
            
        if self.preview:
            if self.pk is None or self.preview.path != self.__original_preview.path:
                self.size = self.preview.size
                self.preview = change_size(self.preview)
                self.preview_date = timezone.now()
            
        if not self.slug:
            title = default_slugify(self.title)  # title on english language
            if not title:
                title = slugify(self.title)  # title on russian language
            strtime = "".join(str(time.time()).split("."))
            self.slug = "%s-%s" % (strtime[7:], title)
        super(Album, self).save(*args, **kwargs)
        

class AlbumLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_album_like')
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE, verbose_name='Album', null=True, related_name='album_like')
        

class AlbumPhoto(models.Model):
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE, verbose_name='Album')
    photo = models.ImageField(verbose_name="Preview", upload_to=upload_to("uploads/albums/photos"))
    size = models.IntegerField(blank=True, verbose_name='Size photo (KB)', null=True)
    photo_date = models.DateTimeField(auto_now_add=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_photo = self.photo
    
    def save(self, *args, **kwargs):
        if self.photo:
            if self.pk is None or self.photo.path != self.__original_photo.path:
                self.size = self.photo.size
                self.photo = change_size(self.photo)
                self.photo_date = timezone.now()
                
        super(AlbumPhoto, self).save(*args, **kwargs)
        

class AlbumWeekView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_album_week')
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE, verbose_name='Album', null=True, related_name='album_week')


class AlbumDayView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_album_day')
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE, verbose_name='Album', null=True, related_name='album_day')


class AlbumView(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    album = models.ForeignKey(
        to=Album, on_delete=models.CASCADE, verbose_name="Album", null=True
    )

    class Meta:
        verbose_name = "View"
        verbose_name_plural = "Views"
        

class AlbumTag(models.Model):
    title = models.CharField(
        verbose_name="Title", max_length=255, blank=False, null=False
    )
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE, verbose_name="Album")

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.title

        
@cleanup.ignore
class DraftAlbum(models.Model):
    preview = models.ImageField(
        verbose_name="Preview", upload_to=upload_to("uploads/albums/drafts/previews"), null=True, blank=True
    )
    title = models.CharField(
        verbose_name="Title", null=True, blank=True, max_length=255
    )
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)
    language = models.CharField(max_length=255, verbose_name='Language', null=True, blank=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category', null=True, blank=True)
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        verbose_name = "Draft"
        verbose_name_plural = "Drafts"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.preview:
            self.preview = change_size(self.preview)
        if not self.blog.is_private and self.level_access:
            self.level_access = 0
        super(DraftAlbum, self).save(*args, **kwargs)
        

class DraftAlbumTag(models.Model):
    title = models.CharField(
        verbose_name="Title", max_length=255, blank=False, null=False
    )
    draft = models.ForeignKey(
        to=DraftAlbum, on_delete=models.CASCADE, verbose_name="Draft"
    )

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.title

        
class DraftAlbumPhoto(models.Model):
    draft_album = models.ForeignKey(to=DraftAlbum, on_delete=models.CASCADE, verbose_name='Draft album')
    photo = models.ImageField(verbose_name="Preview", upload_to=upload_to("uploads/albums/drafts/photos"))
    
    def save(self, *args, **kwargs):
        if self.photo:
            self.photo = change_size(self.photo.path)
        super(DraftAlbumPhoto, self).save(*args, **kwargs)

blog/albums/forms.py
from django import forms
from albums.models import Album, DraftAlbum


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = (
            "preview",
            "title",
        )
        
        
class DraftAlbumForm(forms.ModelForm):
    class Meta:
        model = DraftAlbum
        fields = (
            "preview",
            "title",
            "blog",
        )

blog/albums/templates/albums/create.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Create a album{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input, .btn_remove {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Create a album</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Create a album</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_album" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog" value="{{ blog.pk }}">
              <input type="hidden" name="namespace" value="albums">
              {% csrf_token %}
              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" id="id_description" cols="30" rows="5"></textarea>
              </div>

              <div class="col-12 form-group">
                <label for="id_photo">Photo:</label>
                <input type="file" id="id_photo" name="photo" class="form-control mb-2">
                <button type="button" class="btn btn-primary" id="add_photo">Add more photo</button>
              </div>


              <div class="col-12 form-group">
                <label for="id_language">Language:</label>
                <select id="id_language" class="form-select">
                  <option disabled selected>Select a language</option>
                  <option value="english">English</option>
                  <option value="russian">Russian</option>
                </select>
              </div>

              {% if categories %}
                <div id="categories" class="col-12 form-group">
                  <label for="id_category">Category:</label>
                  <select id="id_category" class="form-select">
                    <option disabled selected>Select a category</option>
                    {% for category in categories %}
                      <option value="{{ category.id }}">{{ category.category_eng }} ({{ category.category_rus }})</option>
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <label>Tags:</label>

                <div id="selected_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <div class="tag" id="div_{{ tag }}" style="margin-bottom: 5px;">
                        <span class="tag-text" id="tags.value">{{ tag }}</span>
                        <img class="img-delete" onclick="delete_tag('{{ tag }}')" src="{% static 'images/cross-svgrepo-com.svg' %}" width="10" height="10" style="margin-top: -1px; cursor: pointer;">
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="d-flex" id="block_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <input name="tags" type="hidden" id="input_{{ tag }}" value="{{ tag }}">
                    {% endfor %}
                  {% endif %}
                  <input type="text" id="tags" class="form-control" />
                  <button type="button" class="btn btn-primary btn_input">Add</button>
                </div>
              </div>

              {% if level_follows %}
                <div class="col-12 form-group">
                  <label for="id_level_access">This is private blog. Select the access level:</label>
                  <select id="id_level_access" class="form-select">
                    <option selected>free</option>
                    {% for level_follow in level_follows %}
                      <option value="{{ level_follow.id }}">Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" class="button button-3d button-black m-0">Publish</button>
                  <button id="id_save" class="button button-3d button-black m-0">Save</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/send_album.js' %}"></script>
  <script src="{% static 'js/get_subcategories.js' %}"></script>
  <script src="{% static 'js/tags.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
  <script>
    document.querySelector('#add_photo').addEventListener('click', function(e) {
      e.target.insertAdjacentHTML('beforebegin', `<input type="file" id="id_photo" name="photo" class="form-control mb-2">`);
    });
  </script>
{% endblock %}

blog/albums/templates/albums/edit.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Edit a album{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input, .btn_remove {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Edit a album</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Edit a album</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_album" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <input type="hidden" value="albums" name="namespace">
              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  {% if form.instance.preview %}
                    <div><img style="object-fit: cover;" src="{{ form.instance.preview.url }}" id="ready_image" alt="" width="640" height="360" /></div>
                  {% else %}
                    <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                  {% endif %}
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{{ form.title.value }}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" id="id_description" cols="30" rows="5">{{ form.instance.description }}</textarea>
              </div>

              <div class="col-12 form-group">
                <label for="id_photo">Photo:</label>
                {% for photo in photos %}
                  <div id="block_img_{{ photo.id }}" class="mb-2">
                    <img src="{{ photo.photo.url }}" width="200">
                    <button type="button" id="delete_photo" class="btn btn-danger" value="{{ photo.id }}">Delete</button>
                  </div>
                {% endfor %}
                <div id="delete_photos">

                </div>
                <button type="button" class="btn btn-primary" id="add_photo">Add more photo</button>
              </div>

              {% if categories %}
                <div id="categories" class="col-12 form-group">
                  <label for="id_category">Category:</label>
                  <select id="id_category" class="form-select">
                    <option disabled selected>Select a category</option>
                    {% for category in categories %}
                      {% if form.instance.category == category %}
                        <option value="{{ category.id }}" selected>{{ category.category_eng }} ({{ category.category_rus }})</option>
                      {% else %}
                        <option value="{{ category.id }}">{{ category.category_eng }} ({{ category.category_rus }})</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              {% if subcategories %}
                <div class="col-12 form-group" id="subcategories">
                  <label for="id_subcategory">Subcategory:</label>
                  <select id="id_subcategory" class="form-select">
                    <option disabled selected>Select a subcategory</option>
                    {% for subcategory in subcategories %}
                      {% if form.instance.subcategory == subcategory %}
                        <option value="{{ subcategory.id }}" selected>{{ subcategory.subcategory_eng }} ({{ subcategory.subcategory_rus }})</option>
                      {% else %}
                        <option value="{{ subcategory.id }}">{{ subcategory.subcategory_eng }} ({{ subcategory.subcategory_rus }})</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <label>Tags:</label>

                <div id="selected_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <div class="tag" id="div_{{ tag.replaced }}" style="margin-bottom: 5px;">
                        <span class="tag-text" id="tags.value">{{ tag }}</span>
                        <img class="img-delete" onclick="delete_tag('{{ tag }}')" src="{% static 'images/cross-svgrepo-com.svg' %}" width="10" height="10" style="margin-top: -1px; cursor: pointer;">
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="d-flex" id="block_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <input name="tags" type="hidden" id="input_{{ tag.replaced }}" value="{{ tag }}">
                    {% endfor %}
                  {% endif %}
                  <input type="text" id="tags" class="form-control" />
                  <button type="button" class="btn btn-primary btn_input">Add</button>
                </div>

              </div>

              {% if level_follows %}
                <div class="col-12 form-group">
                  <label for="id_level_access">This is private blog. Select the access level:</label>
                  <select id="id_level_access" class="form-select">
                    <option selected>free</option>
                    {% for level_follow in level_follows %}
                      {% if level_follow == form.instance.level_access %}
                        <option value="{{ level_follow.level }}" selected>Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                      {% else %}
                        <option value="{{ level_follow.level }}">Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <input type="hidden" value="{{ album_id }}" name="album_id">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <button class="button button-3d button-black m-0">Edit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
  <script src="{% static 'js/edit_album.js' %}"></script>
  <script src="{% static 'js/tags.js' %}"></script>
  <script src="{% static 'js/get_subcategories.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
  <script>
    var btns_delete_photo = document.querySelectorAll('#delete_photo');
    btns_delete_photo.forEach(btn_delete_photo => {
      btn_delete_photo.addEventListener('click', function(e) {
        document.querySelector('#delete_photos').innerHTML = document.querySelector('#delete_photos').innerHTML 
        + `<input type="hidden" name="deleted_photo" value="${e.target.value}">`;
        document.querySelector(`#block_img_${e.target.value}`).remove();
      });
    });
  </script>
  <script>
    document.querySelector('#add_photo').addEventListener('click', function(e) {
      e.target.insertAdjacentHTML('beforebegin', `<input type="file" id="id_photo" name="photo" class="form-control mb-2">`);
    });
  </script>
{% endblock %}