blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import redirect_main
from blog.admin import login, logout

from blogs.views import best_blogs, search, search_tags, main, popular, popular_users

from scheduler.scheduler import TasksScheduler

from .swagger import urlpatterns as urlpatterns_swagger

urlpatterns = [
    # path('admin/login/', login),
    # path('admin/logout/', logout),
    path('admin/', admin.site.urls),

    path('', redirect_main, name="redirect_main"),
    path('main/', main, name="main"),
    path('popular/', popular, name="popular"),
    path('popular_users/', popular_users, name="popular_users"),
    path('best_blogs/', best_blogs, name="best_blogs"),
    path('search/<str:q>/', search, name="search"),
    path('search_tags/<str:q>/', search_tags, name="search_tags"),

    path('', include(('users.urls', 'users'), namespace="users")),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace="blogs")),
    path('posts/', include(('posts.urls', 'posts'), namespace="posts")),
    # path('drafts/', include(('drafts.urls', 'drafts'), namespace="drafts")),
    # path('drafts_survey/', include(('drafts_survey.urls', 'drafts_survey'), namespace="drafts_survey")),
    path('surveys/', include(('surveys.urls', 'surveys'), namespace="surveys")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),
    path('albums/', include(('albums.urls', 'albums'), namespace="albums")),
    path('tests/', include('custom_tests.urls')),
    path('quests/', include('quests.urls')),
    path('companies/', include('campaign.urls')),
    path('periodic_bonuses/', include('periodic_bonuses.urls')),
    path('contests/', include(('contests.urls', 'contests'), namespace="contests")),

    path('summernote/', include('django_summernote.urls')),
    path('api/v1/blogs/', include('blogs.api.urls')),
    path('api/v1/users/', include('users.api.urls')),
    path('api/v1/posts/', include('posts.api.urls')),
    path('api/v1/surveys/', include('surveys.api.urls')),
    # # path('api/v1/drafts/', include('drafts.api.urls')),
    # # path('api/v1/drafts_survey/', include('drafts_survey.api.urls')),
    path('api/v1/comments/', include('comments.api.urls')),
    path('api/v1/notifications/', include('notifications.api.urls')),
    path('api/v1/tests/', include('custom_tests.api.urls')),
    path('api/v1/quests/', include('quests.api.urls')),
    path('api/v1/companies/', include('campaign.api.urls')),
    path('api/v1/periodic_bonuses/', include('periodic_bonuses.api.urls')),
    path('api/v1/albums/', include('albums.api.urls')),
    path('api/v1/contests/', include('contests.api.urls')),
    
    # path('language/<str:language>/', language, name="language"),

    *urlpatterns_swagger
]

# running scheduler
try:
    scheduler = TasksScheduler()
    scheduler.run()
except Exception as e:
    print(f"Scheduler error: {e}")

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/posts/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from blog.routers import CustomRouter
from .views import DraftPostViewSet, PostViewSet

router = CustomRouter()
router.register(r'draft', DraftPostViewSet, basename='draft')
router.register(r'', PostViewSet, basename='post')


urlpatterns = [
    path('', include(router.urls)),
]

blog/posts/urls.py
from django.urls import path
from posts.views import (
    index,
    create, 
    show, 
    edit, 
    best_posts_mouth, 
    draft_post_create,
)


urlpatterns = [
    path('', index, name="index"),
    path('blog/<slug:slug>/create/', create, name='create'),
    path('show/<slug:slug>/', show, name="show"),
    path('edit/<slug:slug>/', edit, name="edit"),
    path('best_posts/30days/', best_posts_mouth, name="best_posts_mouth"),
    # draft
    path('blog/<slug:slug>/draft/create/', draft_post_create, name="draft_post_create"),
]

blog/users/urls.py
from django.urls import path
# from unfold.admin import site
from users.views import *


urlpatterns = [
    path("registration/login/", login_register, name="login_register"),
    path("my/profile/", my_profile, name="my_profile"),
    path("profile/<str:username>/", profile, name="profile"),
    path("forgot_password/", forgot_password, name="forgot_password"),
    path("change_password/<uidb64>/<token>/", change_password, name="change_password"),
    path("edit_profile", edit_profile, name="edit_profile"),
    path("edit_password", edit_password, name="edit_password"),
    path("change_user_status", change_user_status, name="change_user_status"),
    # path("my_page/", site.admin_view(MyCustomPage.as_view()), name="my_page"),
]


# site.register_view(path="my-custom-page/", view=MyCustomPage, name="my_custom_page")

blog/posts/models.py
import os
import time
from django.db import models
from django.conf import settings
from django_cleanup import cleanup
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.template.defaultfilters import slugify as default_slugify
from transliterate import slugify
from django.core.exceptions import ValidationError
from blogs.models import Blog, LevelAccess
from custom_tests.models import Test
from blog.utils import upload_to, change_size
from django.utils import timezone


class LevelAccessManager(models.Manager):
    def get_queryset(self):
        return super(LevelAccessManager, self).get_queryset().filter(level_access=None, is_paid=False)


class Category(models.Model):
    category_rus = models.CharField(verbose_name='Category rus')
    category_eng = models.CharField(verbose_name='Category eng')
    
    def __str__(self):
        return self.category_eng
    
    
class Subcategory(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory_rus = models.CharField(verbose_name='Subcategory rus')
    subcategory_eng = models.CharField(verbose_name='Subcategory eng')

    def __str__(self):
        return self.subcategory_eng
    

class Post(models.Model):
    level_access_objects = LevelAccessManager()
    objects = models.Manager()

    slug = models.SlugField(
        verbose_name="URL", max_length=255, unique=True, db_index=True
    )
    preview = models.ImageField(
        verbose_name="Preview", upload_to=upload_to("uploads/posts/previews"), null=True, blank=True
    )
    size = models.IntegerField(blank=True, verbose_name='Size preview (KB)', null=True)
    title = models.CharField(
        verbose_name="Title", null=False, blank=False, max_length=255
    )
    content = models.TextField(verbose_name="Content")
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    language = models.CharField(
        max_length=255,
        verbose_name="Language"
    )
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    scores = models.IntegerField(verbose_name="scores", default=0)
    mouth_scores = models.IntegerField(verbose_name="Mouth scores", default=0)
    hide_to_user = models.BooleanField(default=False, verbose_name="Hide to user")
    hide_to_moderator = models.BooleanField(
        default=False, verbose_name="Hide to moderator"
    )
    test = models.OneToOneField(to=Test, verbose_name='Test', on_delete=models.CASCADE, null=True, blank=True)
    namespace = models.CharField(verbose_name='Namespace', default='posts')
    add_survey = models.BooleanField(verbose_name="Add survey", default=False)
    is_paid = models.BooleanField(verbose_name="Is paid", default=False)
    amount = models.IntegerField(verbose_name="Amount", blank=True, null=True)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)

    date = models.DateTimeField(auto_now_add=True)
    preview_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_preview = self.preview

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.preview:
            if self.pk is None or self.preview.path != self.__original_preview.path:
                self.size = self.preview.size
                self.preview = change_size(self.preview)
                self.preview_date = timezone.now()
            
        if not self.blog.is_private and self.level_access:
            self.level_access = None
            
        if not self.slug:
            title = default_slugify(self.title)  # title on english language
            if not title:
                title = slugify(self.title)  # title on russian language

            strtime = "".join(str(time.time()).split("."))
            self.slug = "%s-%s" % (strtime[7:], title)
            
        super(Post, self).save(*args, **kwargs)
        

class PostLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_post_like')
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name='Post', null=True, related_name='post_like')
        

class PostRadio(models.Model):
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name='Post')
    scores = models.IntegerField(verbose_name='scores', default=0)
    title = models.CharField(max_length=255, verbose_name="title")
    
    class Meta:
        verbose_name = 'Radio'
        verbose_name_plural = 'Radios'
        
    def __str__(self):
        return self.title


class PostVote(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User')
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name='Post')
    option = models.ForeignKey(to=PostRadio, on_delete=models.CASCADE, verbose_name='Option', null=True)


class PostTag(models.Model):
    title = models.CharField(
        verbose_name="Title", max_length=255, blank=False, null=False
    )
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name="Post")

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.title


class PostWeekView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_post_week')
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name='Post', null=True, related_name='post_week')


class PostDayView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_post_day')
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, verbose_name='Post', null=True, related_name='post_day')


class PostView(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    post = models.ForeignKey(
        to=Post, on_delete=models.CASCADE, verbose_name="Post", null=True
    )

    class Meta:
        verbose_name = "View"
        verbose_name_plural = "Views"
        

class BuyPost(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    post = models.ForeignKey(
        to=Post, on_delete=models.CASCADE, verbose_name="Post"
    )
    scores = models.IntegerField(verbose_name="scores")


@receiver(post_delete, sender=Post)
def on_delete(sender, **kwargs):
    instance = kwargs['instance']
    images = []
    html_str = instance.content

    while "img" in html_str:
        left_enter = html_str.find("<img")
        html_str = html_str[left_enter:]
        right_enter = html_str.find(">") + 1
        images.append(html_str[:right_enter])
        html_str = html_str[right_enter:]

    for image in images:
        left_enter = image.find(settings.MEDIA_URL)
        image = image[left_enter + len(settings.MEDIA_URL) :]
        right_enter = image.find('"')
        path = os.path.join(settings.MEDIA_ROOT / image[:right_enter])
        os.remove(os.path.join(path))
    
    if instance.test:
        instance.test.delete() # delete test


@cleanup.ignore
class DraftPost(models.Model):
    preview = models.ImageField(
        verbose_name="Preview", upload_to=upload_to("uploads/posts/drafts/previews"), null=True, blank=True
    )
    size = models.IntegerField(blank=True, verbose_name='Size preview (KB)', null=True)
    title = models.CharField(
        verbose_name="Title", null=True, blank=True, max_length=255
    )
    content = models.TextField(verbose_name="Content", blank=True, null=True)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)
    language = models.CharField(max_length=255, verbose_name='Language', null=True, blank=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category', null=True, blank=True)
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    add_survey = models.BooleanField(verbose_name="Add survey", default=False)
    is_paid = models.BooleanField(verbose_name="Is paid", default=False)
    is_create_test = models.BooleanField(verbose_name='Test', default=False)
    amount = models.IntegerField(verbose_name="Amount", blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        verbose_name = "Draft"
        verbose_name_plural = "Drafts"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.preview:
            self.preview = change_size(self.preview.path)
            self.size = self.preview.size       
        if not self.blog.is_private and self.level_access:
            self.level_access = 0
        super(DraftPost, self).save()


class DraftPostTag(models.Model):
    title = models.CharField(
        verbose_name="Title", max_length=255, blank=False, null=False
    )
    draft = models.ForeignKey(
        to=DraftPost, on_delete=models.CASCADE, verbose_name="Draft"
    )

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):

blog/posts/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django_summernote import fields

from posts.models import Post, DraftPost


class PostForm(forms.ModelForm):
    content = fields.SummernoteTextFormField(required=False)

    class Meta:
        model = Post
        fields = (
            "preview",
            "title",
            "content",
        )


class DraftForm(forms.ModelForm):
    content = forms.CharField(
        widget=SummernoteWidget(attrs={"summernote": {"width": "100%"}}), required=False
    )

    class Meta:
        model = DraftPost
        fields = (
            "preview",
            "title",
            "content",
            "blog",
        )

blog/posts/templates/posts/best_posts_mouth.html
{% extends "layouts/basic.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<!-- Page Title
============================================= -->
<section class="page-title bg-transparent">
    <div class="container">
        <div class="page-title-row">

            <div class="page-title-content">
                <h1>Blog</h1>
                <span>The best posts in 30 days</span>
            </div>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Blog</li>
                </ol>
            </nav>

        </div>
    </div>
</section><!-- .page-title end -->

<!-- Content -->
<section id="content">
    <div class="content-wrap">
        <div class="container">

            <div class="row gx-5 col-mb-80">
                <!-- Post Content
                ============================================= -->
                <main class="postcontent col-lg-9">

                    <!-- Posts
                    ============================================= -->
                    <div id="posts" class="row grid-container gutter-30">

                        {% for post in posts %}
                            <div class="entry col-12" id="element">
                                <div class="grid-inner">
                                    <div class="entry-image">
                                        {% if post.preview %}
                                            <a href="{{ post.preview.url }}" data-lightbox="image"><img src="{{ post.preview.url }}" alt="Standard Post with Image" width="960" style="object-fit: cover; max-width: 100%; height: 445px;"></a>
                                        {% endif %}
                                    </div>
                                    <div class="entry-title">
                                        <h2><a href="{% url 'posts:show' post.slug %}">{{ post.title }}</a></h2>
                                    </div>
                                    <div class="entry-meta">
                                        <ul>
                                            <li><i class="uil uil-schedule"></i> {{ post.date|date:"d M Y" }}</li>
                                            <li><a href="{% url 'users:profile' post.user.username %}"><i class="uil uil-user"></i> {{ post.user.username }}</a></li>
                                            <li><a href="{% url 'posts:show' post.slug %}"><i class="uil uil-comments-alt"></i> {{ post.count_comments }} Comments</a></li>
                                            <li><img width="16" height="16" style="margin-top: -2px; opacity: 0.5;" src="{% static 'images/icon_eye.png' %}"><span style="margin-left: 8px;">{{ post.count_views }}</span></li>
                                        </ul>
                                    </div>
                                    <div class="entry-content">
                                        <p>{{ post.content|striptags|truncatechars:10 }}</p>
                                        <a href="{% url 'posts:show' post.slug %}" class="more-link">Read More</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div><!-- #posts end -->

                </main><!-- .postcontent end -->

                <!-- Sidebar
                ============================================= -->
                <aside class="sidebar col-lg-3">
                    {% include "layouts/sidebar.html" %}
                </aside><!-- .sidebar end -->
            </div>

        </div>
    </div>
</section><!-- #content end -->

{% endblock %}

{% block js %}
<script src="{% static 'js/functions.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% endblock %}

blog/posts/templates/posts/create.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Create a post{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input, .btn_remove {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Create a post</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Create a post</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_post" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog" value="{{ blog.pk }}">
              <input type="hidden" name="namespace" value="posts">
              {% csrf_token %}
              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_content">Content:</label>
                {{ form.content }}
              </div>

              <div class="col-12 form-group">
                <input id="checkbox-11" class="checkbox-style" name="add_survey" type="checkbox">
                <label for="checkbox-11" class="checkbox-style-3-label">Add survey</label>
              </div>

              <div class="col-12 form-group" id="title_answers" style="display: none;">
                <label>Answer options (There are <span id="num_answers" style="font-weight: bold;">9</span> options left):</label> <button style="display: inline-block;" type="button" class="btn btn-primary" id="add_more">Add more</button>
              </div>

              <div id="answers_block" style="display: none;">
                <div class="col-12 form-group d-flex" id="answer">
                  <input type="text" class="form-control" name="answers">
                  <button type="button" class="btn btn-danger btn_remove" onclick="remove_answer(this)">Remove</button>
                </div>
              </div>

              <div class="col-12 form-group">
                <label for="id_language">Language:</label>
                <select id="id_language" class="form-select">
                  <option disabled selected>Select a language</option>
                  <option value="english">English</option>
                  <option value="russian">Russian</option>
                </select>
              </div>

              {% if categories %}
                <div id="categories" class="col-12 form-group">
                  <label for="id_category">Category:</label>
                  <select id="id_category" class="form-select">
                    <option disabled selected>Select a category</option>
                    {% for category in categories %}
                      <option value="{{ category.id }}">{{ category.category_eng }} ({{ category.category_rus }})</option>
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <input id="checkbox-12" class="checkbox-style" name="is_create_test" type="checkbox">
                <label for="checkbox-12" class="checkbox-style-3-label">Add test</label>
              </div>

              <div class="col-12 form-group">
                <label>Tags:</label>

                <div id="selected_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <div class="tag" id="div_{{ tag }}" style="margin-bottom: 5px;">
                        <span class="tag-text" id="tags.value">{{ tag }}</span>
                        <img class="img-delete" onclick="delete_tag('{{ tag }}')" src="{% static 'images/cross-svgrepo-com.svg' %}" width="10" height="10" style="margin-top: -1px; cursor: pointer;">
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="d-flex" id="block_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <input name="tags" type="hidden" id="input_{{ tag }}" value="{{ tag }}">
                    {% endfor %}
                  {% endif %}
                  <input type="text" id="tags" class="form-control" />
                  <button type="button" class="btn btn-primary btn_input">Add</button>
                </div>
              </div>

              <div class="col-12 form-group">
                <input id="checkbox-10" class="checkbox-style" name="is_paid" type="checkbox">
                <label for="checkbox-10" class="checkbox-style-3-label">is paid</label>
              </div>

              <div class="col-12 form-group form-none" style="display: none;">
                <label for="id_amount">Amount:</label>
                <input type="number" id="id_amount" name="amount" value="{% if form.amount.value %}{{ form.amount.value }}{% endif %}" class="form-control" />
              </div>

              {% if level_follows %}
                <div class="col-12 form-group">
                  <label for="id_level_access">This is private blog. Select the access level:</label>
                  <select id="id_level_access" class="form-select">
                    <option selected>free</option>
                    {% for level_follow in level_follows %}
                      <option value="{{ level_follow.id }}">Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" class="button button-3d button-black m-0">Publish</button>
                  <button id="id_save" class="button button-3d button-black m-0">Save</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/tags.js' %}"></script>
  <script src="{% static 'js/answers.js' %}"></script>
  <script src="{% static 'js/send_post.js' %}"></script>
  <script src="{% static 'js/get_subcategories.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
  <script>
    var _is_paid = document.querySelector('input[name="is_paid"]');
    _is_paid.addEventListener('change', function() {
      if (_is_paid.checked) {
        document.querySelector('.form-none').style.display = 'block';
      } else {
        document.querySelector('.form-none').style.display = 'none';
      }
    });

    var _title_answers = document.querySelector('#title_answers');
    var _answers_block = document.querySelector('#answers_block');
    var _add_survey = document.querySelector('input[name="add_survey"]');

    _add_survey.addEventListener('click', function() {
      if (_add_survey.checked) {
        _title_answers.style.display = 'block';
        _answers_block.style.display = 'block';
      } else {
        _title_answers.style.display = 'none';
        _answers_block.style.display = 'none';
      }
    });
  </script>
  </script>
{% endblock %}