blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import redirect_main
from blog.admin import login, logout

from blogs.views import best_blogs, search, search_tags, main, popular, popular_users

from scheduler.scheduler import TasksScheduler

from .swagger import urlpatterns as urlpatterns_swagger

urlpatterns = [
    # path('admin/login/', login),
    # path('admin/logout/', logout),
    path('admin/', admin.site.urls),

    path('', redirect_main, name="redirect_main"),
    path('main/', main, name="main"),
    path('popular/', popular, name="popular"),
    path('popular_users/', popular_users, name="popular_users"),
    path('best_blogs/', best_blogs, name="best_blogs"),
    path('search/<str:q>/', search, name="search"),
    path('search_tags/<str:q>/', search_tags, name="search_tags"),

    path('', include(('users.urls', 'users'), namespace="users")),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace="blogs")),
    path('posts/', include(('posts.urls', 'posts'), namespace="posts")),
    # path('drafts/', include(('drafts.urls', 'drafts'), namespace="drafts")),
    # path('drafts_survey/', include(('drafts_survey.urls', 'drafts_survey'), namespace="drafts_survey")),
    path('surveys/', include(('surveys.urls', 'surveys'), namespace="surveys")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),
    path('albums/', include(('albums.urls', 'albums'), namespace="albums")),
    path('tests/', include('custom_tests.urls')),
    path('quests/', include('quests.urls')),
    path('companies/', include('campaign.urls')),
    path('periodic_bonuses/', include('periodic_bonuses.urls')),
    path('contests/', include(('contests.urls', 'contests'), namespace="contests")),

    path('summernote/', include('django_summernote.urls')),
    path('api/v1/blogs/', include('blogs.api.urls')),
    path('api/v1/users/', include('users.api.urls')),
    path('api/v1/posts/', include('posts.api.urls')),
    path('api/v1/surveys/', include('surveys.api.urls')),
    # # path('api/v1/drafts/', include('drafts.api.urls')),
    # # path('api/v1/drafts_survey/', include('drafts_survey.api.urls')),
    path('api/v1/comments/', include('comments.api.urls')),
    path('api/v1/notifications/', include('notifications.api.urls')),
    path('api/v1/tests/', include('custom_tests.api.urls')),
    path('api/v1/quests/', include('quests.api.urls')),
    path('api/v1/companies/', include('campaign.api.urls')),
    path('api/v1/periodic_bonuses/', include('periodic_bonuses.api.urls')),
    path('api/v1/albums/', include('albums.api.urls')),
    path('api/v1/contests/', include('contests.api.urls')),
    
    # path('language/<str:language>/', language, name="language"),

    *urlpatterns_swagger
]

# running scheduler
try:
    scheduler = TasksScheduler()
    scheduler.run()
except Exception as e:
    print(f"Scheduler error: {e}")

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/blogs/api/urls.py
from django.urls import path

from blog.routers import CustomRouter
from blogs.api.views import BlogViewSet

router = CustomRouter()
router.register('', BlogViewSet, basename="blogs")
urlpatterns = router.urls
# urlpatterns = [
#     path('create/', create),
#     path('show/<slug:slug>/', show),
#     path('pay/<int:id>/<int:level_access>/', pay),
#     path('edit/<int:id>/', edit),
#     path('delete/<int:id>/', delete),
#     path('delete_follow/<int:id>/', delete_follow),
# ]

blog/blogs/urls.py
from django.urls import path

from blogs.views import (
    create, 
    show, 
    edit, 
    donate,
    donate_show,
    create_level_follow
)


urlpatterns = [
    path('create/', create, name="create"),
    path('show/<slug:slug>/', show, name="show"),
    path('edit/<slug:slug>/', edit, name="edit"),
    path('<slug:slug>/donate/', donate, name="donate"),
    path('show/donate/<int:id>/', donate_show, name="donate_show"),
    path('<slug:slug>/create_level_follow/', create_level_follow, name="create_level_follow"),
]

blog/users/urls.py
from django.urls import path
# from unfold.admin import site
from users.views import *


urlpatterns = [
    path("registration/login/", login_register, name="login_register"),
    path("my/profile/", my_profile, name="my_profile"),
    path("profile/<str:username>/", profile, name="profile"),
    path("forgot_password/", forgot_password, name="forgot_password"),
    path("change_password/<uidb64>/<token>/", change_password, name="change_password"),
    path("edit_profile", edit_profile, name="edit_profile"),
    path("edit_password", edit_password, name="edit_password"),
    path("change_user_status", change_user_status, name="change_user_status"),
    # path("my_page/", site.admin_view(MyCustomPage.as_view()), name="my_page"),
]


# site.register_view(path="my-custom-page/", view=MyCustomPage, name="my_custom_page")

blog/blogs/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinLengthValidator
from blog.utils import upload_to, change_size
from django.utils import timezone


class Blog(models.Model):
    slug = models.CharField(
        verbose_name="URL", null=False, blank=False, validators=[MinLengthValidator(5)], max_length=40, unique=True
    )
    preview = models.ImageField(verbose_name="Preview", upload_to=upload_to("uploads/blogs/follows"))
    size = models.IntegerField(verbose_name='Size preview (KB)', null=True, blank=True)
    title = models.CharField(
        verbose_name="Title", null=False, blank=False, max_length=255
    )
    description = models.TextField(
        verbose_name="Description", null=False, blank=False
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    is_private = models.BooleanField(verbose_name="Is private", default=False)
    date = models.DateTimeField(auto_now_add=True)
    preview_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_preview = self.preview

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if self.preview:
            if self.pk is None or self.preview.path != self.__original_preview.path:
                self.size = self.preview.size
                self.preview = change_size(self.preview)
                self.preview_date = timezone.now()
                
        self.slug = "_".join(self.slug.split())
        super(Blog, self).save()
    

class Donate(models.Model):
    message = models.CharField(verbose_name='Message', max_length=200)
    amount = models.IntegerField(verbose_name='Amount')
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, verbose_name="Blog")
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="User", null=True)
    date = models.DateTimeField(auto_now_add=True)


class LevelAccess(models.Model):
    preview = models.ImageField(verbose_name="Preview", upload_to=upload_to("uploads/blogs/follows"))
    title = models.CharField(max_length=255, verbose_name="Title", unique=True)
    description = models.TextField(verbose_name="Description")
    level = models.IntegerField(verbose_name="Level access")
    scores = models.IntegerField(verbose_name="Scores", default=0)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, verbose_name="Blog")
    size = models.IntegerField(verbose_name='Size preview (KB)', null=True, blank=True)
    preview_date = models.DateTimeField(auto_now_add=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_preview = self.preview
    
    def save(self, *args, **kwargs):
        if self.preview:
            if self.pk is None or self.preview.path != self.__original_preview.path:
                self.size = self.preview.size
                self.preview = change_size(self.preview)
                self.preview_date = timezone.now()
                
        super(LevelAccess, self).save()


class PaidFollow(models.Model):
    follower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="Expiration date", null=True)
    count_months = models.IntegerField(verbose_name="Count months", default=1)
    blog_access_level = models.ForeignKey(
        to=LevelAccess, on_delete=models.CASCADE, verbose_name="blog level access"
    )
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, verbose_name="Blog")


class BlogFollow(models.Model):
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="follower"
    )
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE, verbose_name="Blog")    

blog/blogs/forms.py
from django import forms

from blogs.models import Blog


class BlogForm(forms.ModelForm):  
    class Meta:
        model = Blog
        fields = (
            'preview',
            'title',
            'description'
        )

blog/blog/views.py
from django.shortcuts import redirect


def redirect_main(request):
    return redirect("main")

blog/blogs/templates/blogs/create.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Create a blog{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Create a blog</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Create a blog</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_blog" method="POST" enctype="multipart/form-data">
              {% csrf_token %}

              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>
              
              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" id="id_description" cols="30" rows="5">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
              </div>

              <div class="col-12 form-group">
                <label for="id_url">URL:</label>
                <input type="text" id="id_url" name="url" value="{% if form.url.value %}{{ form.url.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <input id="checkbox-10" class="checkbox-style" name="is_private" type="checkbox">
                <label for="checkbox-10" class="checkbox-style-3-label">Is private blog</label>
              </div>

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" class="button button-3d button-black m-0">Publish</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/send_blog.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
{% endblock %}

blog/blogs/templates/blogs/create_level_follow.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Create a level follow (Level {{ level }}){% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Create a level of follow (Level {{ level }})</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Create a level follow (Level {{ level }})</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_level_follow" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog_id" value="{{ blog.pk }}">
              {% csrf_token %}

              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" id="id_description" cols="30" rows="5">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
              </div>

              <div class="col-12 form-group">
                <label for="id_scores">Scores:</label>
                <input type="number" id="id_scores" name="scores" value="{% if form.scores.value %}{{ form.scores.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" class="button button-3d button-black m-0">Publish</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/send_level_follow.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
{% endblock %}

blog/blogs/templates/blogs/donate.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Donate{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Donate</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Donate</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_donate" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog_id" value="{{ blog_id }}">
              {% csrf_token %}
              
              <div class="col-12 form-group">
                <label for="id_amount">Amount of donation:</label>
                <input type="number" id="id_amount" name="amount" value="{% if form.amount.value %}{{ form.amount.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_message">Message (<span id="characters">200</span> characters left):</label>
                <textarea maxlength="200" id="id_message" name="message" class="form-control" cols="30" rows="5">{% if form.message.value %}{{ form.message.value }}{% endif %}</textarea>
              </div>

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" class="button button-3d button-black m-0">Send</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/donate.js' %}"></script>
  <script>
    var _message = document.querySelector("#id_message");
    _message.addEventListener('input', function() {
      var characters = document.querySelector("#characters")

      if (_message.value.length > 200) {
        characters.innerHTML = 0;
      } else {
        characters.innerHTML = 200 - _message.value.length;
      }
    });
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
{% endblock %}

blog/blogs/templates/blogs/edit.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Edit a blog{% endblock %}

{% block head %}
  <style>
    .dz-success-mark,
    .dz-error-mark,
    .dz-size {
      display: none;
    }
    
    .dropzone .dz-preview .dz-image {
      width: 640px;
      height: 360px;
    }
    
    .btn_input {
      border: none;
      font-size: 14px;
      margin-left: 4px;
    }
    
    .tag {
      background-color: rgba(0, 255, 255, 0.5);
      padding: 5px;
      border-radius: 5px;
      color: black;
      display: inline-block;
    }
  </style>
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Edit a blog</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Edit a blog</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_blog" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog_id" value="{{ blog_id }}">
              {% csrf_token %}
              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  {% if form.instance.preview %}
                    <div><img style="object-fit: cover;" src="{{ form.instance.preview.url }}" id="ready_image" alt="" width="640" height="360" /></div>
                  {% else %}
                    <div><img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" /></div>
                  {% endif %}
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" id="id_description" class="form-control" cols="30" rows="5">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
              </div>

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button type="submit" class="button button-3d button-black m-0">Edit</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/edit_blog.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
{% endblock %}

blog/blogs/templates/blogs/popular_blogs.html
{% extends "layouts/basic.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<!-- Page Title
============================================= -->
<section class="page-title bg-transparent">
    <div class="container">
        <div class="page-title-row">

            <div class="page-title-content">
                <h1>Blog</h1>
                <span>The best blogs</span>
            </div>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Blog</li>
                </ol>
            </nav>

        </div>
    </div>
</section><!-- .page-title end -->

<!-- Content -->
<section id="content">
    <div class="content-wrap">
        <div class="container">

            <div class="row gx-5 col-mb-80">
                <!-- Post Content
                ============================================= -->
                <main class="postcontent col-lg-9">

                    <!-- Posts
                    ============================================= -->
                    <div id="posts" class="row grid-container gutter-30">

                        {% for blog in blogs %}
                            <div class="entry col-12" id="element">
                                <div class="grid-inner">
                                    <div class="entry-image">
                                        <a href="{{ blog.preview.url }}" data-lightbox="image"><img src="{{ blog.preview.url }}" alt="Standard Post with Image" width="960" style="object-fit: cover; max-width: 100%; height: 445px;"></a>
                                    </div>
                                    <div class="entry-title">
                                        <h2><a href="{% url 'blogs:show' blog.slug %}">{{ blog.title }}</a></h2>
                                    </div>
                                    <div class="entry-meta">
                                        <ul>
                                            <li><i class="uil uil-schedule"></i> {{ blog.date|date:"d M Y" }}</li>
                                            <li><a href="{% url 'users:profile' blog.user.username %}"><i class="uil uil-user"></i> {{ blog.user.username }}</a></li>
                                        </ul>
                                    </div>
                                    <div class="entry-content">
                                        <p>{{ blog.description }}</p>
                                        <a href="{% url 'blogs:show' blog.slug %}" class="more-link">Read More</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div><!-- #posts end -->

                </main><!-- .postcontent end -->


                <!-- Sidebar
                ============================================= -->
                <aside class="sidebar col-lg-3">
                    {% include "layouts/sidebar.html" %}
                </aside><!-- .sidebar end -->
            </div>

        </div>
    </div>
</section><!-- #content end -->

{% endblock %}

{% block js %}
<script src="{% static 'js/functions.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% endblock %}