blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import redirect_main
from blog.admin import login, logout

from blogs.views import best_blogs, search, search_tags, main, popular, popular_users

from scheduler.scheduler import TasksScheduler

from .swagger import urlpatterns as urlpatterns_swagger

urlpatterns = [
    # path('admin/login/', login),
    # path('admin/logout/', logout),
    path('admin/', admin.site.urls),

    path('', redirect_main, name="redirect_main"),
    path('main/', main, name="main"),
    path('popular/', popular, name="popular"),
    path('popular_users/', popular_users, name="popular_users"),
    path('best_blogs/', best_blogs, name="best_blogs"),
    path('search/<str:q>/', search, name="search"),
    path('search_tags/<str:q>/', search_tags, name="search_tags"),

    path('', include(('users.urls', 'users'), namespace="users")),
    path('blogs/', include(('blogs.urls', 'blogs'), namespace="blogs")),
    path('posts/', include(('posts.urls', 'posts'), namespace="posts")),
    # path('drafts/', include(('drafts.urls', 'drafts'), namespace="drafts")),
    # path('drafts_survey/', include(('drafts_survey.urls', 'drafts_survey'), namespace="drafts_survey")),
    path('surveys/', include(('surveys.urls', 'surveys'), namespace="surveys")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),
    path('albums/', include(('albums.urls', 'albums'), namespace="albums")),
    path('tests/', include('custom_tests.urls')),
    path('quests/', include('quests.urls')),
    path('companies/', include('campaign.urls')),
    path('periodic_bonuses/', include('periodic_bonuses.urls')),
    path('contests/', include(('contests.urls', 'contests'), namespace="contests")),

    path('summernote/', include('django_summernote.urls')),
    path('api/v1/blogs/', include('blogs.api.urls')),
    path('api/v1/users/', include('users.api.urls')),
    path('api/v1/posts/', include('posts.api.urls')),
    path('api/v1/surveys/', include('surveys.api.urls')),
    # # path('api/v1/drafts/', include('drafts.api.urls')),
    # # path('api/v1/drafts_survey/', include('drafts_survey.api.urls')),
    path('api/v1/comments/', include('comments.api.urls')),
    path('api/v1/notifications/', include('notifications.api.urls')),
    path('api/v1/tests/', include('custom_tests.api.urls')),
    path('api/v1/quests/', include('quests.api.urls')),
    path('api/v1/companies/', include('campaign.api.urls')),
    path('api/v1/periodic_bonuses/', include('periodic_bonuses.api.urls')),
    path('api/v1/albums/', include('albums.api.urls')),
    path('api/v1/contests/', include('contests.api.urls')),
    
    # path('language/<str:language>/', language, name="language"),

    *urlpatterns_swagger
]

# running scheduler
try:
    scheduler = TasksScheduler()
    scheduler.run()
except Exception as e:
    print(f"Scheduler error: {e}")

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/surveys/api/urls.py
from django.urls import path, include
# from rest_framework.routers import DefaultRouter
from .views import SurveyViewSet, DraftSurveyViewSet
from blog.routers import CustomRouter

router = CustomRouter()
router.register(r'', SurveyViewSet, basename='survey')
router.register(r'draft', DraftSurveyViewSet, basename='survey_draft')

urlpatterns = [
    path('', include(router.urls)),
]

blog/surveys/urls.py
from django.urls import path

from surveys.views import create, edit, show, index, draft_survey_create


urlpatterns = [
    path('', index, name="index"),
    path('blog/<slug:slug>/create/', create, name='create'),
    path('edit/<slug:slug>/', edit, name="edit"),
    path('show/<slug:slug>/', show, name="show"),
    
    # draft
    path('blog/<slug:slug>/draft/create/', draft_survey_create, name="draft_survey_create"),
]

blog/surveys/models.py
import time
from blog.utils import upload_to, change_size
from django.db import models
from django.conf import settings
from django_cleanup import cleanup
from django.template.defaultfilters import slugify as default_slugify
from transliterate import slugify
from blogs.models import Blog, LevelAccess
from blog.managers import LevelAccessManager
from django.utils import timezone


class Category(models.Model):
    category_rus = models.CharField(verbose_name='Category rus')
    category_eng = models.CharField(verbose_name='Category eng')
    
    def __str__(self):
        return self.category_eng
    
    
class Subcategory(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory_rus = models.CharField(verbose_name='Subcategory rus')
    subcategory_eng = models.CharField(verbose_name='Subcategory eng')

    def __str__(self):
        return self.subcategory_eng


class Survey(models.Model):
    objects = models.Manager()
    level_access_objects = LevelAccessManager()
    
    slug = models.SlugField(verbose_name='URL', max_length=255, unique=True, db_index=True)
    preview = models.ImageField(verbose_name='Preview', upload_to=upload_to('uploads/surveys/previews'), null=True, blank=True)
    size = models.IntegerField(blank=True, verbose_name='Size preview (KB)', null=True)
    title = models.CharField(verbose_name='Title', null=False, blank=False, max_length=255)
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    content = models.TextField(verbose_name='Content', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    language = models.CharField(max_length=255, verbose_name='Language')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category')
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    namespace = models.CharField(verbose_name='Namespace', default='surveys')
    hide_to_user = models.BooleanField(default=False, verbose_name='Hide to user')
    hide_to_moderator = models.BooleanField(default=False, verbose_name='Hide to moderator')
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)
    
    date = models.DateTimeField(auto_now_add=True)
    preview_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'Survey'
        verbose_name_plural = 'Surveys'
        
    def __str__(self):
        return self.title
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_preview = self.preview
    
    def save(self, *args, **kwargs):
        if self.preview:
            if self.pk is None or self.preview.path != self.__original_preview.path:
                self.size = self.preview.size
                self.preview = change_size(self.preview)
                self.preview_date = timezone.now()
                
        if not self.blog.is_private and self.level_access:
            self.level_access = None
            
        if not self.slug:
            title = default_slugify(self.title) # title on english language
            if not title:
                title = slugify(self.title) # title on russian language
                
            strtime = "".join(str(time.time()).split("."))
            self.slug = "%s-%s" % (strtime[7:], title)
        super(Survey, self).save(*args, **kwargs)
        

class SurveyTag(models.Model):
    title = models.CharField(verbose_name='Title', max_length=255, blank=False, null=False)
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey')
    
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        
    def __str__(self):
        return self.title
    

class SurveyLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_survey_like')
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey', null=True, related_name='survey_like')
    

class SurveyWeekView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_survey_week')
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey', null=True, related_name='survey_week')


class SurveyDayView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='user_survey_day')
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey', null=True, related_name='survey_day')
    

class SurveyView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user', on_delete=models.CASCADE, null=True)
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey', null=True)
    
    class Meta:
        verbose_name = 'View'
        verbose_name_plural = 'Views'
        

class SurveyRadio(models.Model):
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey')
    scores = models.IntegerField(verbose_name='scores', default=0)
    title = models.CharField(max_length=255, verbose_name="title")
    
    class Meta:
        verbose_name = 'Radio'
        verbose_name_plural = 'Radios'
        
    def __str__(self):
        return self.title


class SurveyVote(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User')
    survey = models.ForeignKey(to=Survey, on_delete=models.CASCADE, verbose_name='Survey')
    option = models.ForeignKey(to=SurveyRadio, on_delete=models.CASCADE, verbose_name='Option', null=True)

@cleanup.ignore
class DraftSurvey(models.Model):
    preview = models.ImageField(
        verbose_name="Preview",
        upload_to=upload_to("uploads/surveys/drafts/previews"),
        null=True,
        blank=True,
    )
    size = models.IntegerField(blank=True, verbose_name='Size preview (KB)', null=True)
    title = models.CharField(
        verbose_name="Title", null=True, blank=True, max_length=255
    )
    description = models.TextField(verbose_name="Description", null=True, blank=True)
    content = models.TextField(verbose_name="Content", blank=True, null=True)
    language = models.CharField(max_length=255, verbose_name='Language', null=True, blank=True)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Category', null=True, blank=True)
    subcategory = models.ForeignKey(to=Subcategory, on_delete=models.CASCADE, verbose_name='Subcategory', null=True, blank=True)
    blog = models.ForeignKey(to=Blog, on_delete=models.CASCADE)
    level_access = models.ForeignKey(to=LevelAccess, on_delete=models.CASCADE, verbose_name='Level access', null=True, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )

    class Meta:
        verbose_name = "Draft"
        verbose_name_plural = "Drafts"

    def save(self, *args, **kwargs):
        if self.preview:
            self.size = self.preview.size
            self.preview = change_size(self.preview.path)
        if not self.blog.is_private and self.level_access:
            self.level_access = 0
        super(DraftSurvey, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class DraftSurveyTag(models.Model):
    title = models.CharField(
        verbose_name="Title", max_length=255, blank=False, null=False
    )
    draft_survey = models.ForeignKey(
        to=DraftSurvey, on_delete=models.CASCADE, verbose_name="Draft survey"
    )

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.title


class DraftSurveyRadio(models.Model):
    draft_survey = models.ForeignKey(
        to=DraftSurvey, on_delete=models.CASCADE, verbose_name="Draft survey"
    )
    title = models.CharField(max_length=255, verbose_name="title")

    class Meta:
        verbose_name = "Radio"
        verbose_name_plural = "Radios"

    def __str__(self):
        return self.title

blog/surveys/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from django_summernote import fields

from surveys.models import Survey, DraftSurvey


class SurveyForm(forms.ModelForm):
    content = fields.SummernoteTextFormField(required=False)

    class Meta:
        model = Survey
        fields = (
            "preview",
            "title",
            "description",
            "content",
        )


# draft
class DraftSurveyForm(forms.ModelForm):
    content = forms.CharField(
        widget=SummernoteWidget(attrs={"summernote": {"width": "100%"}}), required=False
    )

    class Meta:
        model = DraftSurvey
        fields = (
            "preview",
            "title",
            "description",
            "content",
        )

blog/surveys/templates/drafts_survey/create.html
{% extends 'layouts/basic.html' %}
{% load static %}

{% block title %}Create a survey{% endblock %}

{% block head %}
  <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
{% endblock %}

{% block content %}
<style>
  .dz-success-mark,
  .dz-error-mark,
  .dz-size {
    display: none;
  }
  
  .dropzone .dz-preview .dz-image {
    width: 640px;
    height: 360px;
  }
  
  .btn_input {
    border: none;
    font-size: 14px;
    margin-left: 4px;
  }

  .btn_remove {
    border: none;
    font-size: 14px;
    margin-left: 4px;
  }
  
  .tag {
    background-color: rgba(0, 255, 255, 0.5);
    padding: 5px;
    border-radius: 5px;
    color: black;
    display: inline-block;
  }
</style>
  <!--   Page Title
=============================================   -->
  <section class="page-title bg-transparent">
    <div class="container">
      <div class="page-title-row">
        <div class="page-title-content">
          <h1>Create a survey</h1>
        </div>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'main' %}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Create a post</li>
          </ol>
        </nav>
      </div>
    </div>
  </section>
  <!-- .page-title end -->

  <!--   Content
=============================================   -->
  <section id="content">
    <div class="content-wrap">
      <div class="container">
        <div class="accordion accordion-lg mx-auto mb-0" style="max-width: 1000px;">
          <div>
            <form class="row mb-0" id="form_survey" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="blog" value="{{ blog.pk }}">
              {% csrf_token %}
              <div class="col-12 form-group">
                <label>Preview:</label>
                <label for="id_preview" class="bg-dark p-3 text-center text-light" style="word-wrap: break-word; display: block;">
                  <img src="{% static 'images/upload.svg' %}" width="20" height="20" />
                  Select a file or drag it here for preview
                  <div>

                    {% if draft_survey.preview %}
                      <img style="object-fit: cover;" src="{{ draft_survey.preview.url }}" id="ready_image" alt="" width="640" height="360" />
                    {% else %}
                      <img style="object-fit: cover; display: none;" src="#" id="ready_image" alt="" width="640" height="360" />
                    {% endif %}
                  </div>
                </label>
                <input type="file" id="id_preview" style="display: none;" name="preview" />
              </div>

              <div class="col-12 form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" value="{{ draft_survey.title }}" class="form-control" />
              </div>

              <div class="col-12 form-group">
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" id="id_description" cols="30" rows="5">{{ draft_survey.description }}</textarea>
              </div>

              <div class="col-12 form-group">
                <label for="id_content">Content:</label>
                {{ form.content }}
              </div>

              <div class="col-12 form-group" id="title_answers">
                <label>Answer options (There are <span id="num_answers" style="font-weight: bold;">9</span> options left):</label> <button style="display: inline-block;" type="button" class="btn btn-primary" id="add_more">Add more</button>
              </div>

              <div id="answers_block">
                {% if answers %}
                  {% for answer in answers %}
                    <div class="col-12 form-group d-flex" id="answer">
                      <input type="text" class="form-control" name="answers" value="{{ answer.title }}" id="{{ answer.pk }}">
                      <button type="button" class="btn btn-danger btn_remove" onclick="remove_answer(this)">Remove</button>
                    </div>
                  {% endfor %}
                {% else %}
                  <div class="col-12 form-group d-flex" id="answer">
                    <input type="text" class="form-control" name="answers">
                    <button type="button" class="btn btn-danger btn_remove" onclick="remove_answer(this)">Remove</button>
                  </div>
                {% endif %}

              </div>

              <div class="col-12 form-group">
                <label for="id_language">Language:</label>
                <select id="id_language" class="form-select">
                  {% if draft_survey.language == 'english' %}
                    <option disabled>Select a language</option>
                    <option value="english" selected>English</option>
                    <option value="russian">Russian</option>
                  {% elif draft_survey.language == 'russian' %}
                    <option disabled>Select a language</option>
                    <option value="english">English</option>
                    <option value="russian" selected>Russian</option>
                  {% else %}
                    <option disabled selected>Select a language</option>
                    <option value="english">English</option>
                    <option value="russian">Russian</option>
                  {% endif %}
                  
                </select>
              </div>

              {% if categories %}
                <div id="categories" class="col-12 form-group">
                  <label for="id_category">Category:</label>
                  <select id="id_category" class="form-select">
                    <option disabled selected>Select a category</option>
                    {% for category in categories %}
                      {% if draft_survey.category == category %}
                        <option value="{{ category.id }}" selected>{{ category.category_eng }} ({{ category.category_rus }})</option>
                      {% else %}
                        <option value="{{ category.id }}">{{ category.category_eng }} ({{ category.category_rus }})</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              {% if subcategories %}
                <div class="col-12 form-group" id="subcategories">
                  <label for="id_subcategory">Subcategory:</label>
                  <select id="id_subcategory" class="form-select">
                    <option disabled selected>Select a subcategory</option>
                    {% for subcategory in subcategories %}
                      {% if draft_survey.subcategory == subcategory %}
                        <option value="{{ subcategory.id }}" selected>{{ subcategory.subcategory_eng }} ({{ subcategory.subcategory_rus }})</option>
                      {% else %}
                        <option value="{{ subcategory.id }}">{{ subcategory.subcategory_eng }} ({{ subcategory.subcategory_rus }})</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <label>Tags:</label>

                <div id="selected_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <div class="tag" id="div_{{ tag.replaced }}" style="margin-bottom: 5px;">
                        <span class="tag-text" id="tags.value">{{ tag }}</span>
                        <img class="img-delete" onclick="delete_tag('{{ tag }}')" src="{% static 'images/cross-svgrepo-com.svg' %}" width="10" height="10" style="margin-top: -1px; cursor: pointer;">
                      </div>
                    {% endfor %}
                  {% endif %}
                </div>
                <div class="d-flex" id="block_tags">
                  {% if tags %}
                    {% for tag in tags %}
                      <input name="tags" type="hidden" id="input_{{ tag.replaced }}" value="{{ tag }}">
                    {% endfor %}
                  {% endif %}
                  <input type="text" id="tags" class="form-control" />
                  <button type="button" class="btn btn-primary btn_input">Add</button>
                </div>

              </div>

              {% if level_follows %}
                <div class="col-12 form-group">
                  <label for="id_level_access">This is private blog. Select the access level:</label>
                  <select id="id_level_access" class="form-select">
                    <option selected>free</option>
                    {% for level_follow in level_follows %}
                      {% if level_follow == draft_survey.level_access %}
                        <option value="{{ level_follow.level }}" selected>Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                      {% else %}
                        <option value="{{ level_follow.level }}">Level {{ level_follow.level }} ({{ level_follow.scores }} scores)</option>
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              {% endif %}

              <div class="col-12 form-group">
                <input type="hidden" id="g_recaptcha_response" name="g_recaptcha_response">
                <div class="d-flex justify-content-between">
                  <button id="id_publish" type="submit" class="button button-3d button-black m-0">Publish</button>
                  <button id="id_save" type="submit" class="button button-3d button-black m-0">Save</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- #content end -->
{% endblock %}

{% block js %}
  <script src="{% static 'js/functions.js' %}"></script>
  <script src="{% static 'js/tags.js' %}"></script>
  <script src="{% static 'js/send_survey.js' %}"></script>
  <script src="{% static 'js/answers.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
    
        reader.onload = function (e) {
          $('#ready_image').attr('src', e.target.result);
		  $('#ready_image').css('display', 'inline');
        }
    
        reader.readAsDataURL(input.files[0])
      }
    }
    
    $('#id_preview').change(function () {
      readURL(this)
    })
  </script>
  <script>
    function get_g_token() {
      //global grecaptcha
      grecaptcha.ready(function() {
        grecaptcha.execute('{{recaptcha_site_key}}').then(function(token) {
            document.getElementById('g_recaptcha_response').value = token;
        });
      });
    }
  
    get_g_token();
  </script>
{% endblock %}